from scrapli.exceptions import SSHNotFound as SSHNotFound
from typing import Any, List, Type, TypeVar

class PtyProcessError(Exception): ...
PtyProcessType = TypeVar('PtyProcessType', bound='PtyProcess')
_EOF: Any
_INTR: Any

def _make_eof_intr() -> None: ...
def _setwinsize(fd: int, rows: int, cols: int) -> None: ...

class PtyProcess:
    pid: Any = ...
    fd: Any = ...
    fileobj: Any = ...
    terminated: bool = ...
    closed: bool = ...
    exitstatus: Any = ...
    signalstatus: Any = ...
    status: Any = ...
    flag_eof: bool = ...
    delayafterclose: float = ...
    delayafterterminate: float = ...
    def __init__(self, pid: int, fd: int) -> None: ...
    @classmethod
    def spawn(cls: Type[PtyProcessType], spawn_command: List[str], rows: int=..., cols: int=...) -> PtyProcessType: ...
    def __repr__(self) -> str: ...
    def __del__(self) -> None: ...
    def close(self, force: bool=...) -> None: ...
    def flush(self) -> None: ...
    def read(self, size: int=...) -> bytes: ...
    def write(self, bytes_to_write: bytes, flush: bool=...) -> int: ...
    def eof(self) -> bool: ...
    def terminate(self, force: bool=...) -> bool: ...
    def isalive(self) -> bool: ...
    def kill(self, sig: int) -> None: ...
    def setwinsize(self, rows: int=..., cols: int=...) -> None: ...
