from scrapli.exceptions import ConnectionNotOpened as ConnectionNotOpened, ScrapliTimeout as ScrapliTimeout
from typing import Any

class Socket:
    logger: Any = ...
    host: Any = ...
    port: Any = ...
    timeout: Any = ...
    sock: Any = ...
    def __init__(self, host: str, port: int, timeout: int) -> None: ...
    def __bool__(self) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def socket_open(self) -> None: ...
    def socket_close(self) -> None: ...
    def socket_isalive(self) -> bool: ...
