from scrapli.decorators import operation_timeout as operation_timeout, requires_open_session as requires_open_session
from scrapli.exceptions import ScrapliAuthenticationFailed as ScrapliAuthenticationFailed, ScrapliTimeout as ScrapliTimeout
from scrapli.helper import get_prompt_pattern as get_prompt_pattern, strip_ansi as strip_ansi
from scrapli.ssh_config import SSHConfig as SSHConfig
from scrapli.transport.ptyprocess import PtyProcess as PtyProcess
from scrapli.transport.transport import Transport as Transport
from subprocess import Popen
from typing import Any, Dict, Optional

PopenBytes = Popen[bytes]
SYSTEM_SSH_TRANSPORT_ARGS: Any

class SystemSSHTransport(Transport):
    auth_username: Any = ...
    auth_private_key: Any = ...
    auth_password: Any = ...
    auth_strict_key: Any = ...
    auth_bypass: Any = ...
    _timeout_ops: Any = ...
    _comms_prompt_pattern: Any = ...
    _comms_return_char: Any = ...
    _comms_ansi: Any = ...
    ssh_known_hosts_file: Any = ...
    session: Any
    lib_auth_exception: Any = ...
    _isauthenticated: bool = ...
    transport_options: Any = ...
    open_cmd: Any = ...
    _stdin_fd: int = ...
    _stdout_fd: int = ...
    def __init__(self, host: str=..., port: int=..., auth_username: str=..., auth_private_key: str=..., auth_password: str=..., auth_strict_key: bool=..., auth_bypass: bool=..., timeout_socket: int=..., timeout_transport: int=..., timeout_ops: int=..., timeout_exit: bool=..., keepalive: bool=..., keepalive_interval: int=..., keepalive_type: str=..., keepalive_pattern: str=..., comms_prompt_pattern: str=..., comms_return_char: str=..., comms_ansi: bool=..., ssh_config_file: str=..., ssh_known_hosts_file: str=..., transport_options: Optional[Dict[str, Any]]=...) -> None: ...
    ssh_config_file: Any = ...
    def _process_ssh_config(self, ssh_config_file: str) -> None: ...
    def _build_open_cmd(self) -> None: ...
    def open(self) -> None: ...
    def _open_pipes(self) -> bool: ...
    def _ssh_message_handler(self, output: bytes) -> None: ...
    def _pipes_isauthenticated(self, pipes_session: PopenBytes) -> bool: ...
    def _open_pty(self, skip_auth: bool=...) -> bool: ...
    def _pty_authenticate(self, pty_session: PtyProcess) -> None: ...
    def _pty_isauthenticated(self, pty_session: PtyProcess) -> bool: ...
    def close(self) -> None: ...
    def isalive(self) -> bool: ...
    def read(self) -> bytes: ...
    def write(self, channel_input: str) -> None: ...
    timeout_transport: Any = ...
    def set_timeout(self, timeout: Optional[int]=...) -> None: ...
    def _keepalive_standard(self) -> None: ...
