from scrapli.decorators import operation_timeout as operation_timeout
from scrapli.exceptions import ScrapliAuthenticationFailed as ScrapliAuthenticationFailed, ScrapliTimeout as ScrapliTimeout
from scrapli.helper import get_prompt_pattern as get_prompt_pattern, strip_ansi as strip_ansi
from scrapli.ssh_config import SSHConfig as SSHConfig
from scrapli.transport.ptyprocess import PtyProcess as PtyProcess
from scrapli.transport.transport import Transport as Transport
from subprocess import Popen
from typing import Any, Optional

PopenBytes = Popen[bytes]
LOG: Any
SYSTEM_SSH_TRANSPORT_ARGS: Any

class SystemSSHTransport(Transport):
    auth_username: Any = ...
    auth_private_key: Any = ...
    auth_password: Any = ...
    auth_strict_key: Any = ...
    auth_bypass: Any = ...
    ssh_known_hosts_file: Any = ...
    session: Any
    lib_auth_exception: Any = ...
    open_cmd: Any = ...
    def __init__(self, host: str=..., port: int=..., auth_username: str=..., auth_private_key: str=..., auth_password: str=..., auth_strict_key: bool=..., auth_bypass: bool=..., timeout_socket: int=..., timeout_transport: int=..., timeout_ops: int=..., timeout_exit: bool=..., keepalive: bool=..., keepalive_interval: int=..., keepalive_type: str=..., keepalive_pattern: str=..., comms_prompt_pattern: str=..., comms_return_char: str=..., comms_ansi: bool=..., ssh_config_file: str=..., ssh_known_hosts_file: str=...) -> None: ...
    def open(self) -> None: ...
    def close(self) -> None: ...
    def isalive(self) -> bool: ...
    def read(self) -> bytes: ...
    def write(self, channel_input: str) -> None: ...
    timeout_transport: Any = ...
    def set_timeout(self, timeout: Optional[int]=...) -> None: ...
