from typing import Optional

class ScrapliException(Exception): ...
class ScrapliModuleNotFound(ScrapliException): ...
class ScrapliTypeError(ScrapliException): ...
class ScrapliValueError(ScrapliException): ...
class ScrapliUnsupportedPlatform(ScrapliException): ...
class ScrapliTransportPluginError(ScrapliException): ...

class ScrapliConnectionNotOpened(ScrapliException):
    message: str = ...
    def __init__(self, message: Optional[str]=...) -> None: ...

class ScrapliAuthenticationFailed(ScrapliException): ...
class ScrapliConnectionError(ScrapliException): ...
class ScrapliTimeout(ScrapliException): ...
class ScrapliCommandFailure(ScrapliException): ...
class ScrapliPrivilegeError(ScrapliException): ...
