class ScrapliException(Exception): ...
class ScrapliTimeout(ScrapliException): ...
class ScrapliKeepaliveFailure(ScrapliException): ...
class MissingDependencies(ScrapliException): ...
class KeyVerificationFailed(ScrapliException): ...
class ScrapliAuthenticationFailed(ScrapliException): ...
class UnknownPrivLevel(ScrapliException): ...
class CouldNotAcquirePrivLevel(ScrapliException): ...
