from io import TextIOWrapper
from scrapli.exceptions import ScrapliValueError as ScrapliValueError
from scrapli.logging import logger as logger
from typing import Any, Dict, List, Optional, TextIO, Union

def _textfsm_get_template(platform: str, command: str) -> Optional[TextIO]: ...
def _textfsm_to_dict(structured_output: Union[List[Any], Dict[str, Any]], header: List[str]) -> Union[List[Any], Dict[str, Any]]: ...
def textfsm_parse(template: Union[str, TextIOWrapper], output: str, to_dict: bool=...) -> Union[List[Any], Dict[str, Any]]: ...
def genie_parse(platform: str, command: str, output: str) -> Union[List[Any], Dict[str, Any]]: ...
def ttp_parse(template: Union[str, TextIOWrapper], output: str) -> Union[List[Any], Dict[str, Any]]: ...
def resolve_file(file: str) -> str: ...
def format_user_warning(title: str, message: str) -> str: ...
def user_warning(title: str, message: str) -> None: ...
