from io import TextIOWrapper
from typing import Any, Dict, List, Pattern, Union

def get_prompt_pattern(prompt: str, class_prompt: str) -> Pattern[bytes]: ...
def normalize_lines(output: bytes) -> bytes: ...
def strip_ansi(output: bytes) -> bytes: ...
def textfsm_parse(template: Union[str, TextIOWrapper], output: str, to_dict: bool=...) -> Union[List[Any], Dict[str, Any]]: ...
def genie_parse(platform: str, command: str, output: str) -> Union[List[Any], Dict[str, Any]]: ...
def resolve_ssh_config(ssh_config_file: str) -> str: ...
def resolve_ssh_known_hosts(ssh_known_hosts: str) -> str: ...
