from io import TextIOWrapper
from scrapli.exceptions import TransportPluginError as TransportPluginError
from typing import Any, Dict, List, Optional, Pattern, TextIO, Tuple, Union

def _find_transport_plugin(transport: str) -> Tuple[Any, Tuple[str, ...]]: ...
def get_prompt_pattern(prompt: str, class_prompt: str) -> Pattern[bytes]: ...
def normalize_lines(output: bytes) -> bytes: ...
def strip_ansi(output: bytes) -> bytes: ...
def _textfsm_get_template(platform: str, command: str) -> Optional[TextIO]: ...
def _textfsm_to_dict(structured_output: Union[List[Any], Dict[str, Any]], header: List[str]) -> Union[List[Any], Dict[str, Any]]: ...
def textfsm_parse(template: Union[str, TextIOWrapper], output: str, to_dict: bool=...) -> Union[List[Any], Dict[str, Any]]: ...
def genie_parse(platform: str, command: str, output: str) -> Union[List[Any], Dict[str, Any]]: ...
def resolve_ssh_config(ssh_config_file: str) -> str: ...
def resolve_ssh_known_hosts(ssh_known_hosts: str) -> str: ...
def resolve_file(file: str) -> str: ...
