from scrapli.helper import genie_parse as genie_parse, textfsm_parse as textfsm_parse
from typing import Any, Dict, List, Optional, Union

class Response:
    host: Any = ...
    start_time: Any = ...
    finish_time: Any = ...
    elapsed_time: Any = ...
    channel_input: Any = ...
    textfsm_platform: Any = ...
    genie_platform: Any = ...
    raw_result: str = ...
    result: str = ...
    failed_when_contains: Any = ...
    failed: bool = ...
    def __init__(self, host: str, channel_input: str, textfsm_platform: str=..., genie_platform: str=..., failed_when_contains: Optional[Union[str, List[str]]]=...) -> None: ...
    def __bool__(self) -> bool: ...
    def textfsm_parse_output(self, to_dict: bool=...) -> Union[Dict[str, Any], List[Any]]: ...
    def genie_parse_output(self) -> Union[Dict[str, Any], List[Any]]: ...
