from scrapli.driver import NetworkDriver as NetworkDriver
from scrapli.driver.network_driver import PrivilegeLevel as PrivilegeLevel
from typing import Any, Callable, Dict, Optional

def iosxe_on_open(conn: NetworkDriver) -> None: ...
def iosxe_on_close(conn: NetworkDriver) -> None: ...

PRIVS: Any

class IOSXEDriver(NetworkDriver):
    privs: Any = ...
    default_desired_priv: str = ...
    textfsm_platform: str = ...
    genie_platform: str = ...
    failed_when_contains: Any = ...
    def __init__(self, comms_prompt_pattern: str=..., on_open: Optional[Callable[..., Any]]=..., on_close: Optional[Callable[..., Any]]=..., auth_secondary: str=..., **kwargs: Dict[str, Any]) -> None: ...
