from scrapli.driver import NetworkDriver as NetworkDriver
from scrapli.driver.base_network_driver import PrivilegeLevel as PrivilegeLevel
from scrapli.driver.core.cisco_nxos.base_driver import NXOSDriverBase as NXOSDriverBase, PRIVS as PRIVS
from typing import Any, Callable, Dict, List, Optional

def nxos_on_open(conn: NetworkDriver) -> None: ...
def nxos_on_close(conn: NetworkDriver) -> None: ...

class NXOSDriver(NetworkDriver, NXOSDriverBase):
    def __init__(self, privilege_levels: Optional[Dict[str, PrivilegeLevel]]=..., default_desired_privilege_level: str=..., auth_secondary: str=..., on_open: Optional[Callable[..., Any]]=..., on_close: Optional[Callable[..., Any]]=..., textfsm_platform: str=..., genie_platform: str=..., failed_when_contains: Optional[List[str]]=..., transport: str=..., **kwargs: Dict[str, Any]) -> None: ...
    _current_priv_level: Any = ...
    def _abort_config(self) -> None: ...
    def register_configuration_session(self, session_name: str) -> None: ...
