from scrapli.channel import AsyncChannel as AsyncChannel
from scrapli.driver.base.base_driver import BaseDriver as BaseDriver
from scrapli.exceptions import ScrapliValueError as ScrapliValueError
from scrapli.transport import ASYNCIO_TRANSPORTS as ASYNCIO_TRANSPORTS
from types import TracebackType
from typing import Any, Optional, Type

class AsyncDriver(BaseDriver):
    channel: Any = ...
    def __init__(self, **kwargs: Any) -> None: ...
    async def __aenter__(self) -> AsyncDriver: ...
    async def __aexit__(self, exception_type: Optional[Type[BaseException]], exception_value: Optional[BaseException], traceback: Optional[TracebackType]) -> None: ...
    async def open(self) -> None: ...
    async def close(self) -> None: ...
