from scrapli.channel import Channel as Channel
from scrapli.driver.base.base_driver import BaseDriver as BaseDriver
from scrapli.exceptions import ScrapliValueError as ScrapliValueError
from scrapli.transport import ASYNCIO_TRANSPORTS as ASYNCIO_TRANSPORTS
from types import TracebackType
from typing import Any, Optional, Type

class Driver(BaseDriver):
    channel: Any = ...
    def __init__(self, **kwargs: Any) -> None: ...
    def __enter__(self) -> Driver: ...
    def __exit__(self, exception_type: Optional[Type[BaseException]], exception_value: Optional[BaseException], traceback: Optional[TracebackType]) -> None: ...
    def open(self) -> None: ...
    def close(self) -> None: ...
