from scrapli.decorators import TransportTimeout as TransportTimeout
from scrapli.exceptions import ScrapliConnectionError as ScrapliConnectionError, ScrapliConnectionNotOpened as ScrapliConnectionNotOpened, ScrapliUnsupportedPlatform as ScrapliUnsupportedPlatform
from scrapli.transport.base import BasePluginTransportArgs as BasePluginTransportArgs, BaseTransportArgs as BaseTransportArgs, Transport as Transport
from scrapli.transport.plugins.system.ptyprocess import PtyProcess as PtyProcess
from typing import Any

class PluginTransportArgs(BasePluginTransportArgs):
    auth_username: str
    auth_private_key: str = ...
    auth_strict_key: bool = ...
    ssh_config_file: str = ...
    ssh_known_hosts_file: str = ...
    def __init__(self, auth_username: Any, auth_private_key: Any, auth_strict_key: Any, ssh_config_file: Any, ssh_known_hosts_file: Any) -> None: ...

class SystemTransport(Transport):
    plugin_transport_args: Any = ...
    open_cmd: Any = ...
    session: Any = ...
    def __init__(self, base_transport_args: BaseTransportArgs, plugin_transport_args: PluginTransportArgs) -> None: ...
    def _build_open_cmd(self) -> None: ...
    def open(self) -> None: ...
    def close(self) -> None: ...
    def isalive(self) -> bool: ...
    def read(self) -> bytes: ...
    def write(self, channel_input: bytes) -> None: ...
