from scrapli.channel.base_channel import ChannelBase as ChannelBase
from scrapli.decorators import operation_timeout as operation_timeout
from scrapli.helper import get_prompt_pattern as get_prompt_pattern, strip_ansi as strip_ansi
from scrapli.transport.transport import Transport as Transport
from typing import Any, List, Optional, Tuple

class Channel(ChannelBase):
    transport: Any
    def __init__(self, transport: Transport, **kwargs: Any) -> None: ...
    def _read_chunk(self) -> bytes: ...
    def _read_until_input(self, channel_input: bytes, auto_expand: Optional[bool]=...) -> bytes: ...
    def _read_until_prompt(self, output: bytes=..., prompt: str=...) -> bytes: ...
    def get_prompt(self) -> str: ...
    def send_input(self, channel_input: str, strip_prompt: bool=...) -> Tuple[bytes, bytes]: ...
    def _send_input(self, channel_input: str, strip_prompt: bool) -> Tuple[bytes, bytes]: ...
    def send_inputs_interact(self, interact_events: List[Tuple[str, str, Optional[bool]]]) -> Tuple[bytes, bytes]: ...
