from collections import UserList
from enum import Enum
from logging import Logger
from scrapli.exceptions import UnknownPrivLevel as UnknownPrivLevel
from scrapli.helper import resolve_file as resolve_file
from scrapli.response import Response as Response
from typing import Any, Dict, List, Optional, Tuple, Union

ScrapliMultiResponse = UserList[Response]

class PrivilegeLevel:
    __slots__: Any = ...
    pattern: Any = ...
    name: Any = ...
    previous_priv: Any = ...
    deescalate: Any = ...
    escalate: Any = ...
    escalate_auth: Any = ...
    escalate_prompt: Any = ...
    def __init__(self, pattern: str, name: str, previous_priv: str, deescalate: str, escalate: str, escalate_auth: bool, escalate_prompt: str) -> None: ...

DUMMY_PRIV_LEVEL: Any
PRIVS: Dict[str, PrivilegeLevel]

class PrivilegeAction(Enum):
    NO_ACTION: str = ...
    ESCALATE: str = ...
    DEESCALATE: str = ...

class NetworkDriverBase:
    logger: Logger
    comms_prompt_pattern: str
    _current_priv_level: Any = ...
    _priv_map: Dict[str, List[str]]
    failed_when_contains: Optional[List[str]]
    privilege_levels: Dict[str, PrivilegeLevel]
    auth_secondary: str
    textfsm_platform: str
    genie_platform: str
    @staticmethod
    def _check_kwargs_comms_prompt_pattern(kwargs: Any) -> None: ...
    def _generate_comms_prompt_pattern(self) -> None: ...
    def _build_priv_map(self) -> None: ...
    def update_privilege_levels(self, update_channel: bool=...) -> None: ...
    def _determine_current_priv(self, current_prompt: str) -> List[str]: ...
    def _get_privilege_level_name(self, requested_priv: str) -> str: ...
    def _update_response(self, response: Response) -> None: ...
    def register_configuration_session(self, session_name: str) -> None: ...
    def _pre_escalate(self, escalate_priv: PrivilegeLevel) -> None: ...
    def _pre_acquire_priv(self, desired_priv: str) -> Tuple[str, List[str]]: ...
    def _process_acquire_priv(self, resolved_priv: str, map_to_desired_priv: List[str], current_prompt: str) -> Tuple[PrivilegeAction, PrivilegeLevel]: ...
    @staticmethod
    def _pre_send_config(config: str) -> List[str]: ...
    def _post_send_config(self, config: str, multi_response: ScrapliMultiResponse) -> Response: ...
    def _pre_send_configs(self, configs: List[str], failed_when_contains: Optional[Union[str, List[str]]]=..., privilege_level: str=...) -> Tuple[str, Optional[Union[str, List[str]]]]: ...
    def _post_send_configs(self, responses: ScrapliMultiResponse) -> ScrapliMultiResponse: ...
    @staticmethod
    def _pre_send_configs_from_file(file: str) -> List[str]: ...
