from scrapli.channel import Channel as Channel
from scrapli.driver.base_driver import ASYNCIO_TRANSPORTS as ASYNCIO_TRANSPORTS, ScrapeBase as ScrapeBase
from scrapli.exceptions import TransportPluginError as TransportPluginError
from types import TracebackType
from typing import Any, Optional, Type

class Scrape(ScrapeBase):
    channel: Any = ...
    def __init__(self, **kwargs: Any) -> None: ...
    def __enter__(self) -> Scrape: ...
    def __exit__(self, exception_type: Optional[Type[BaseException]], exception_value: Optional[BaseException], traceback: Optional[TracebackType]) -> None: ...
    def open(self) -> None: ...
    def close(self) -> None: ...
    @property
    def timeout_ops(self) -> float: ...
    _timeout_ops: Any = ...
    @timeout_ops.setter
    def timeout_ops(self, timeout_value: float) -> None: ...
