from scrapli.driver.driver import Scrape as Scrape
from scrapli.response import Response as Response
from typing import Any, List, Optional, Tuple, Union

class GenericDriver(Scrape):
    def __init__(self, comms_prompt_pattern: str=..., comms_ansi: bool=..., **kwargs: Any) -> None: ...
    def send_command(self, command: str, strip_prompt: bool=..., failed_when_contains: Optional[Union[str, List[str]]]=...) -> Response: ...
    def send_commands(self, commands: List[str], strip_prompt: bool=..., failed_when_contains: Optional[Union[str, List[str]]]=...) -> List[Response]: ...
    def send_interactive(self, interact_events: List[Tuple[str, str, Optional[bool]]], failed_when_contains: Optional[Union[str, List[str]]]=...) -> Response: ...
    def get_prompt(self) -> str: ...
