import socket
from scrapli.exceptions import ScrapliConnectionNotOpened as ScrapliConnectionNotOpened
from scrapli.logging import get_instance_logger as get_instance_logger
from typing import Any, Set

class Socket:
    logger: Any = ...
    host: Any = ...
    port: Any = ...
    timeout: Any = ...
    sock: Any = ...
    def __init__(self, host: str, port: int, timeout: float) -> None: ...
    def __bool__(self) -> bool: ...
    def _connect(self, socket_address_families: Set[socket.AddressFamily]) -> None: ...
    def open(self) -> None: ...
    def close(self) -> None: ...
    def isalive(self) -> bool: ...
